import esbuild from "esbuild";
import fs from "fs";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const prod = process.argv[2] === "production";

// `src/entry.ts` registers the OCR backends that ship here. An optional `pro/` folder, present only
// in the maintainer's working copy, registers additional ones on top; `src/` never references it, so
// this builds unchanged wherever `pro/` is absent.
//
// Set TAGGED_SYNC_BUILD=free to force the `src/` entry point even when `pro/` is present -- that is
// how you run exactly what users get without moving any files. Works for `dev` too.
const forceBase = process.env.TAGGED_SYNC_BUILD === "free";
const entryPoint = !forceBase && fs.existsSync("pro/entry.ts") ? "pro/entry.ts" : "src/entry.ts";
console.log(`entry: ${entryPoint}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		// KaitaiStream (kaitai-struct) lazily requires this for encodings we never use; not an
		// installed dependency, so it must stay external rather than be bundled. Same fix as the
		// inspect:rm dev script's --external:iconv-lite.
		"iconv-lite",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
