import esbuild from "esbuild";
import process from "process";
// Node's own list, via `node:module`. The `builtin-modules` package did the same thing and is
// flagged by the store's `depend/ban-dependencies` check as a needless dependency.
import { builtinModules as builtins } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const prod = process.argv[2] === "production";

// One entry point and one output. `src/entry.ts` registers every backend, including the paid ones
// in `pro/`, which are unlocked at runtime by the licence rather than by which file was built. What
// you see here is what users get.
const entryPoint = "src/entry.ts";
console.log(`entry: ${entryPoint}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	// Keeps Obsidian's automated review happy. `rmapi-js` depends on jszip, whose `browser` field
	// resolves the package to the pre-built `dist/jszip.min.js`; that bundle has `setimmediate` and
	// `immediate` (via `lie`) baked in, and their environment probes create `<script>` elements and
	// call `new Function` -- 4 + 1 sites that the store's scanner reads out of `main.js` and rejects.
	// Pointing jszip at its own source lets those two polyfills resolve as ordinary packages, so
	// they can be swapped for the shims in `src/shims/`. See .scratch/public-repo-and-pipeline.
	alias: {
		jszip: "jszip/lib/index.js",
		setimmediate: "./src/shims/setimmediate.ts",
		lie: "./src/shims/lie.cjs",
	},
	// Rewrites free-identifier `fetch` references inside the bundle (rmapi-js has no fetch
	// injection point) to the CORS-free requestUrl shim. Bundle-scoped: the global fetch of the
	// Obsidian process is never touched. Rationale in src/obsidian-fetch.ts.
	inject: ["src/fetch-shim.ts"],
	external: [
		"obsidian",
		"electron",
		// KaitaiStream (kaitai-struct) lazily requires this for encodings we never use; not an
		// installed dependency, so it must stay external rather than be bundled. Same fix as the
		// inspect:rm dev script's --external:iconv-lite.
		"iconv-lite",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
