import esbuild from "esbuild";
import fs from "fs";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const prod = process.argv[2] === "production";

// `src/entry.ts` registers the OCR backends that ship here, and it is what a plain build of this
// repo produces -- what you see is what users get. An optional `pro/` folder, present only in the
// maintainer's working copy, registers additional backends on top; building it is an explicit
// opt-in via TAGGED_SYNC_BUILD=pro (which fails loudly if `pro/` is absent, rather than silently
// producing the free build).
const pro = process.env.TAGGED_SYNC_BUILD === "pro";
if (pro && !fs.existsSync("pro/entry.ts")) {
	throw new Error("TAGGED_SYNC_BUILD=pro but pro/entry.ts does not exist in this checkout");
}
const entryPoint = pro ? "pro/entry.ts" : "src/entry.ts";
console.log(`entry: ${entryPoint}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	// Rewrites free-identifier `fetch` references inside the bundle (rmapi-js has no fetch
	// injection point) to the CORS-free requestUrl shim. Bundle-scoped: the global fetch of the
	// Obsidian process is never touched. Rationale in src/obsidian-fetch.ts.
	inject: ["src/fetch-shim.ts"],
	external: [
		"obsidian",
		"electron",
		// KaitaiStream (kaitai-struct) lazily requires this for encodings we never use; not an
		// installed dependency, so it must stay external rather than be bundled. Same fix as the
		// inspect:rm dev script's --external:iconv-lite.
		"iconv-lite",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
