import type { Content, Entry } from "rmapi-js";
import { describe, expect, it, vi } from "vitest";
import { formatLocalMinute } from "./frontmatter";
import { backfillFrontmatter, cleanupFrontmatter } from "./frontmatter-pass";
import type { NoteStore } from "./note-builder";
import { FRONTMATTER_KEYS_VERSION, isStaleFrontmatter, type SyncIndex, type SyncIndexRow } from "./sync-engine";

const BODY = "> [!info]- Generated by Tagged Sync — do not edit\n\n![[x.pdf]]\n<!-- tagged-sync:end -->\n";
const SYNCED_AT = "2026-08-01T10:00:00.000Z";
const SYNCED_MINUTE = formatLocalMinute(new Date(SYNCED_AT));

function row(overrides: Partial<SyncIndexRow>): SyncIndexRow {
	return {
		syncKey: "doc-1:sync",
		docId: "doc-1",
		pageId: null,
		tag: "sync",
		entryHash: "hash-1",
		pageHash: null,
		notePath: "Target/Notebook.md",
		status: "active",
		syncedAt: SYNCED_AT,
		...overrides,
	};
}

function fakeNoteStore(files: Record<string, string>): NoteStore & { files: Record<string, string> } {
	return {
		files,
		read: vi.fn(async (path: string) => files[path] ?? null),
		exists: vi.fn(async (path: string) => path in files),
		write: vi.fn(async (path: string, content: string) => {
			files[path] = content;
		}),
		move: vi.fn(),
		ensureFolder: vi.fn(),
	};
}

function documentEntry(overrides: Partial<Entry> = {}): Entry {
	return {
		id: "doc-1",
		hash: "hash-1",
		visibleName: "Notebook",
		lastModified: String(Date.UTC(2026, 6, 31, 8, 0)),
		pinned: true,
		parent: "folder-1",
		type: "DocumentType",
		fileType: "notebook",
		tags: [{ name: "projekt x", timestamp: 0 }],
		...overrides,
	} as Entry;
}

function folderEntry(overrides: Partial<Entry> = {}): Entry {
	return {
		id: "folder-1",
		hash: "hash-folder",
		visibleName: "Work",
		lastModified: "0",
		pinned: false,
		parent: "",
		type: "CollectionType",
		...overrides,
	} as Entry;
}

function fakeApi(entries: Entry[], contentById: Record<string, Partial<Content>>) {
	return {
		listItems: vi.fn(async () => entries),
		getContent: vi.fn(async (id: string) => {
			const content = contentById[id];
			if (!content) throw new Error(`no content for ${id}`);
			return content as Content;
		}),
	};
}

describe("backfillFrontmatter (toggle on)", () => {
	it("writes the keys into every already-synced note, from the device's own metadata", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:sync": row({}) } };
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": { fileType: "notebook" } });

		const result = await backfillFrontmatter(api, store, index);

		expect(result).toEqual({ written: 1, skipped: 0 });
		const note = store.files["Target/Notebook.md"];
		expect(note).toContain("tags:\n  - remarkable/projekt-x\n  - remarkable/sync\n");
		expect(note).toContain(`remarkable-synced: ${SYNCED_MINUTE}\n`);
		expect(note).toContain("remarkable-folder: Work\n");
		expect(note).toContain("remarkable-type: notebook\n");
		expect(note).toContain("remarkable-pinned: true\n");
		expect(note).toContain("remarkable-uuid: doc-1\n");
		// The row now knows which tags are the plugin's to remove again.
		expect(index.rows["doc-1:sync"].frontmatterTags).toEqual(["remarkable/projekt-x", "remarkable/sync"]);
	});

	it("skips what it cannot reach -- a document gone from the device, a note gone from the vault -- and says how many", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: {
				"doc-1:sync": row({}),
				"doc-gone:sync": row({ syncKey: "doc-gone:sync", docId: "doc-gone", notePath: "Target/Gone.md" }),
				"doc-1:note-gone": row({ syncKey: "doc-1:note-gone", tag: "note-gone", notePath: "Target/Missing.md" }),
			},
		};
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": { fileType: "notebook" } });

		const result = await backfillFrontmatter(api, store, index);

		expect(result).toEqual({ written: 1, skipped: 2 });
		expect(index.rows["doc-gone:sync"].frontmatterTags).toBeUndefined();
	});

	it("skips a document whose content cannot be read, and still writes the rest", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY, "Target/Other.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: {
				"doc-1:sync": row({}),
				"doc-2:sync": row({ syncKey: "doc-2:sync", docId: "doc-2", notePath: "Target/Other.md" }),
			},
		};
		// doc-2 has an entry but no content -- the fake throws, like a cloud read that fails mid-pass.
		const api = fakeApi([documentEntry(), documentEntry({ id: "doc-2" }), folderEntry()], { "doc-1": {} });

		const result = await backfillFrontmatter(api, store, index);

		expect(result).toEqual({ written: 1, skipped: 1 });
		expect(store.files["Target/Other.md"]).toBe(BODY);
	});

	it("names an annotated PDF a pdf and a book an epub", async () => {
		const store = fakeNoteStore({ "Target/Paper.md": BODY, "Target/Book.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: {
				"doc-pdf:sync": row({ syncKey: "doc-pdf:sync", docId: "doc-pdf", notePath: "Target/Paper.md" }),
				"doc-epub:sync": row({ syncKey: "doc-epub:sync", docId: "doc-epub", notePath: "Target/Book.md" }),
			},
		};
		const api = fakeApi(
			[documentEntry({ id: "doc-pdf", fileType: "pdf" }), documentEntry({ id: "doc-epub", fileType: "epub" }), folderEntry()],
			{ "doc-pdf": { fileType: "pdf" }, "doc-epub": { fileType: "epub" } },
		);

		await backfillFrontmatter(api, store, index);

		expect(store.files["Target/Paper.md"]).toContain("remarkable-type: pdf\n");
		expect(store.files["Target/Book.md"]).toContain("remarkable-type: epub\n");
	});

	it("leaves orphaned rows alone -- their tag is unmapped, their notes are the user's now", async () => {
		const store = fakeNoteStore({ "Target/Old.md": BODY });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:old": row({ syncKey: "doc-1:old", tag: "old", notePath: "Target/Old.md", status: "orphaned" }) } };
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": {} });

		const result = await backfillFrontmatter(api, store, index);

		expect(result).toEqual({ written: 0, skipped: 0 });
		expect(store.files["Target/Old.md"]).toBe(BODY);
		expect(api.listItems).not.toHaveBeenCalled();
	});
});

describe("cleanupFrontmatter (toggle off)", () => {
	it("removes the plugin's keys and tracked tags from every note the index knows, and forgets the tracking", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:sync": row({}) } };
		await backfillFrontmatter(fakeApi([documentEntry(), folderEntry()], { "doc-1": {} }), store, index);

		const cleaned = await cleanupFrontmatter(store, index);

		expect(cleaned).toBe(1);
		expect(store.files["Target/Notebook.md"]).toBe(BODY);
		expect(index.rows["doc-1:sync"].frontmatterTags).toBeUndefined();
	});

	it("keeps the user's own frontmatter and reports zero when there was nothing of the plugin's", async () => {
		const userNote = "---\nrating: 5\n---\n" + BODY;
		const store = fakeNoteStore({ "Target/Notebook.md": userNote });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:sync": row({}) } };

		expect(await cleanupFrontmatter(store, index)).toBe(0);
		expect(store.files["Target/Notebook.md"]).toBe(userNote);
	});

	it("cleans an orphaned row's note too -- it may still sit in the vault", async () => {
		const withKeys = "---\nremarkable-uuid: doc-1\n---\n" + BODY;
		const store = fakeNoteStore({ "Target/Old.md": withKeys });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:old": row({ syncKey: "doc-1:old", notePath: "Target/Old.md", status: "orphaned" }) } };

		expect(await cleanupFrontmatter(store, index)).toBe(1);
		expect(store.files["Target/Old.md"]).toBe(BODY);
	});
});

describe("backfillFrontmatter and the page keys (#107)", () => {
	/** A modern document: its page order is in `cPages`, so the pass needs no file listing. */
	function modernContent(pageIds: string[], fileType = "notebook"): Partial<Content> {
		return {
			fileType,
			cPages: { pages: pageIds.map((id, i) => ({ id, idx: { timestamp: "1:1", value: String.fromCharCode(97 + i) } })) },
		} as Partial<Content>;
	}

	it("counts the pages of the note: every page for a notebook row, one for a page row", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY, "Target/Page.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: {
				"doc-1:sync": row({}),
				"doc-1:page-b:todo": row({ syncKey: "doc-1:page-b:todo", pageId: "page-b", tag: "todo", notePath: "Target/Page.md" }),
			},
		};
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": modernContent(["page-a", "page-b", "page-c"]) });

		await backfillFrontmatter(api, store, index);

		expect(store.files["Target/Notebook.md"]).toContain("remarkable-pages: 3\n");
		expect(store.files["Target/Page.md"]).toContain("remarkable-pages: 1\n");
	});

	it("writes a page row's position in the document, and none for a notebook row", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY, "Target/Page.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: {
				"doc-1:sync": row({}),
				"doc-1:page-b:todo": row({ syncKey: "doc-1:page-b:todo", pageId: "page-b", tag: "todo", notePath: "Target/Page.md" }),
			},
		};
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": modernContent(["page-a", "page-b", "page-c"]) });

		await backfillFrontmatter(api, store, index);

		expect(store.files["Target/Page.md"]).toContain("remarkable-page: 2\n");
		// A notebook note covers pages 1..3 and has no current page -- an absent key, not a 1.
		expect(store.files["Target/Notebook.md"]).not.toContain("remarkable-page:");
	});

	it("leaves both page keys out for a legacy document whose page list needs the file listing", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:sync": row({}) } };
		// A legacy `pages[]` notebook: its live pages can only be told from the document's files, which
		// this pass does not fetch. Better no key than a count that is too high; the document's next
		// real sync writes the right one.
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": { fileType: "notebook", pages: ["page-a", "page-b"] } as Partial<Content> });

		await backfillFrontmatter(api, store, index);

		expect(store.files["Target/Notebook.md"]).not.toContain("remarkable-pages:");
		expect(store.files["Target/Notebook.md"]).not.toContain("remarkable-page:");
	});

	it("still counts one page for a page row whose page has gone from the device, and gives it no position", async () => {
		const store = fakeNoteStore({ "Target/Page.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: { "doc-1:page-z:todo": row({ syncKey: "doc-1:page-z:todo", pageId: "page-z", tag: "todo", notePath: "Target/Page.md" }) },
		};
		// The tagged page was deleted on the device, so it is not in the document's page order any
		// more. The note is still one page of work; it simply has no position to name.
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": modernContent(["page-a", "page-b"]) });

		await backfillFrontmatter(api, store, index);

		expect(store.files["Target/Page.md"]).toContain("remarkable-pages: 1\n");
		expect(store.files["Target/Page.md"]).not.toContain("remarkable-page:");
	});

	it("names an annotated PDF and a book by their type while carrying the identity keys", async () => {
		const store = fakeNoteStore({ "Target/Pdf.md": BODY, "Target/Book.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: {
				"doc-pdf:sync": row({ syncKey: "doc-pdf:sync", docId: "doc-pdf", notePath: "Target/Pdf.md" }),
				"doc-epub:sync": row({ syncKey: "doc-epub:sync", docId: "doc-epub", notePath: "Target/Book.md" }),
			},
		};
		const api = fakeApi([documentEntry({ id: "doc-pdf" }), documentEntry({ id: "doc-epub" }), folderEntry()], {
			"doc-pdf": modernContent(["page-a"], "pdf"),
			"doc-epub": modernContent(["page-a", "page-b"], "epub"),
		});

		await backfillFrontmatter(api, store, index, { newNoteId: () => "minted" });

		expect(store.files["Target/Pdf.md"]).toContain("remarkable-type: pdf\n");
		expect(store.files["Target/Pdf.md"]).toContain("remarkable-uuid: doc-pdf\n");
		expect(store.files["Target/Pdf.md"]).toContain("remarkable-note-id: minted\n");
		expect(store.files["Target/Book.md"]).toContain("remarkable-type: epub\n");
		expect(store.files["Target/Book.md"]).toContain("remarkable-uuid: doc-epub\n");
		expect(store.files["Target/Book.md"]).toContain("remarkable-note-id: minted\n");
	});
});

describe("backfillFrontmatter and the note identity (#109)", () => {
	it("mints an id for a row that has none, and leaves it alone on a second run", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:sync": row({}) } };
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": { fileType: "notebook" } });
		let minted = 0;
		const newNoteId = () => `note-${++minted}`;

		await backfillFrontmatter(api, store, index, { newNoteId });
		const first = index.rows["doc-1:sync"].noteId;
		const afterFirstRun = store.files["Target/Notebook.md"];

		await backfillFrontmatter(api, store, index, { newNoteId });

		expect(first).toBe("note-1");
		// The second run must not mint again: an identity automation keys on cannot be regenerated.
		expect(index.rows["doc-1:sync"].noteId).toBe("note-1");
		expect(minted).toBe(1);
		expect(store.files["Target/Notebook.md"]).toBe(afterFirstRun);
	});

	it("stamps the key-set version, so the one-time pass does not run over the same row twice", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY, "Target/Other.md": BODY });
		const index: SyncIndex = {
			rootHash: "r",
			rows: {
				"doc-1:sync": row({ frontmatterVersion: FRONTMATTER_KEYS_VERSION }),
				"doc-1:other": row({ syncKey: "doc-1:other", tag: "other", notePath: "Target/Other.md" }),
			},
		};
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": { fileType: "notebook" } });

		const result = await backfillFrontmatter(api, store, index, { select: isStaleFrontmatter });

		// Only the unstamped row is written; the stamped one is already current.
		expect(result).toEqual({ written: 1, skipped: 0 });
		expect(store.files["Target/Notebook.md"]).toBe(BODY);
		expect(index.rows["doc-1:other"].frontmatterVersion).toBe(FRONTMATTER_KEYS_VERSION);
	});

	it("forgets the key-set stamp on cleanup but keeps the note's identity", async () => {
		const store = fakeNoteStore({ "Target/Notebook.md": BODY });
		const index: SyncIndex = { rootHash: "r", rows: { "doc-1:sync": row({}) } };
		const api = fakeApi([documentEntry(), folderEntry()], { "doc-1": { fileType: "notebook" } });
		await backfillFrontmatter(api, store, index, { newNoteId: () => "note-1" });

		await cleanupFrontmatter(store, index);

		expect(index.rows["doc-1:sync"].frontmatterVersion).toBeUndefined();
		// Turning the feature back on gives the note the identity it had, not a new one.
		expect(index.rows["doc-1:sync"].noteId).toBe("note-1");
	});
});
