import { describe, expect, it } from "vitest";
import {
	applyFrontmatter,
	deviceModified,
	formatLocalMinute,
	frontmatterAllowed,
	namespacedTags,
	removeFrontmatter,
	type NoteFrontmatter,
} from "./frontmatter";
import { entitlementOf, NO_LICENCE, startTrial } from "./licence-state";

const NOW = new Date("2026-08-26T12:00:00.000Z");

function fields(overrides: Partial<NoteFrontmatter> = {}): NoteFrontmatter {
	return {
		tags: ["remarkable/projekt-x"],
		modified: "2026-08-25T16:20",
		synced: "2026-08-25T17:02",
		folder: "Work/Projekt X",
		type: "notebook",
		pages: 12,
		page: null,
		pinned: true,
		uuid: "aaaa0002-0000-0000-0000-000000000000",
		noteId: "n0000001",
		...overrides,
	};
}

const BODY = "> [!info]- Generated by Tagged Sync — do not edit\n\n![[x.pdf]]\n<!-- tagged-sync:end -->\n";

describe("applyFrontmatter on a note without frontmatter", () => {
	it("writes the block of the spec example, keys in its order", () => {
		const { content } = applyFrontmatter(BODY, fields(), []);
		expect(content).toBe(
			"---\n" +
				"tags:\n" +
				"  - remarkable/projekt-x\n" +
				"remarkable-modified: 2026-08-25T16:20\n" +
				"remarkable-synced: 2026-08-25T17:02\n" +
				"remarkable-folder: Work/Projekt X\n" +
				"remarkable-type: notebook\n" +
				"remarkable-pages: 12\n" +
				"remarkable-pinned: true\n" +
				"remarkable-uuid: aaaa0002-0000-0000-0000-000000000000\n" +
				"remarkable-note-id: n0000001\n" +
				"---\n" +
				BODY,
		);
	});

	it("hands back the tags it now owns, for the index row", () => {
		const { ownTags } = applyFrontmatter(BODY, fields({ tags: ["remarkable/a", "remarkable/b"] }), []);
		expect(ownTags).toEqual(["remarkable/a", "remarkable/b"]);
	});

	it("writes no folder key for a document at the device root", () => {
		const { content } = applyFrontmatter(BODY, fields({ folder: null }), []);
		expect(content).not.toContain("remarkable-folder");
	});

	it("is idempotent", () => {
		const once = applyFrontmatter(BODY, fields(), []);
		const twice = applyFrontmatter(once.content, fields(), once.ownTags);
		expect(twice.content).toBe(once.content);
	});
});

describe("applyFrontmatter on a note the user already gave frontmatter", () => {
	it("preserves every user line byte-for-byte, comments and odd spacing included", () => {
		const existing = "---\nalias:   Meeting   notes\n# my comment\nrating: 5\n---\n" + BODY;
		const { content } = applyFrontmatter(existing, fields(), []);
		expect(content).toContain("alias:   Meeting   notes\n# my comment\nrating: 5\n");
	});

	it("restores a deleted plugin key and repairs a hand-edited value", () => {
		const once = applyFrontmatter(BODY, fields(), []).content;
		const tampered = once.replace("remarkable-uuid: aaaa0002-0000-0000-0000-000000000000\n", "").replace("remarkable-type: notebook", "remarkable-type: diary");
		const { content } = applyFrontmatter(tampered, fields(), ["remarkable/projekt-x"]);
		expect(content).toContain("remarkable-uuid: aaaa0002-0000-0000-0000-000000000000\n");
		expect(content).toContain("remarkable-type: notebook\n");
	});

	it("removes its folder line once the document moved to the device root", () => {
		const once = applyFrontmatter(BODY, fields(), []).content;
		const { content } = applyFrontmatter(once, fields({ folder: null }), ["remarkable/projekt-x"]);
		expect(content).not.toContain("remarkable-folder");
	});

	it("quotes a folder YAML would misread", () => {
		const { content } = applyFrontmatter(BODY, fields({ folder: "Work: Notes" }), []);
		expect(content).toContain('remarkable-folder: "Work: Notes"\n');
	});
});

describe("the shared tags key", () => {
	it("merges its tags into a user block list without touching the user's entries", () => {
		const existing = "---\ntags:\n  - daily\n  - '#quoted'\n---\n" + BODY;
		const { content } = applyFrontmatter(existing, fields({ tags: ["remarkable/x"] }), []);
		expect(content).toContain("tags:\n  - daily\n  - '#quoted'\n  - remarkable/x\n");
	});

	it("removes only the tags it added itself when they leave the device, never user tags", () => {
		const existing = "---\ntags:\n  - daily\n  - remarkable/old\n  - remarkable/kept\n---\n" + BODY;
		const { content } = applyFrontmatter(existing, fields({ tags: ["remarkable/kept"] }), ["remarkable/old", "remarkable/kept"]);
		expect(content).toContain("tags:\n  - daily\n  - remarkable/kept\n");
		expect(content).not.toContain("remarkable/old");
	});

	it("joins an inline list in place", () => {
		const existing = "---\ntags: [daily, remarkable/old]\n---\n" + BODY;
		const { content } = applyFrontmatter(existing, fields({ tags: ["remarkable/new"] }), ["remarkable/old"]);
		expect(content).toContain("tags: [daily, remarkable/new]\n");
	});

	it("grows a bare scalar into a list that still holds the user's entry", () => {
		const existing = "---\ntags: daily\n---\n" + BODY;
		const { content } = applyFrontmatter(existing, fields({ tags: ["remarkable/x"] }), []);
		expect(content).toContain("tags:\n  - daily\n  - remarkable/x\n");
	});

	it("does not duplicate a tag the note already carries", () => {
		const existing = "---\ntags:\n  - remarkable/x\n---\n" + BODY;
		const { content } = applyFrontmatter(existing, fields({ tags: ["remarkable/x"] }), ["remarkable/x"]);
		expect(content.match(/remarkable\/x/g)).toHaveLength(1);
	});
});

describe("removeFrontmatter (the toggle-off cleanup)", () => {
	it("takes the whole block away when the plugin wrote all of it", () => {
		const once = applyFrontmatter(BODY, fields(), []);
		expect(removeFrontmatter(once.content, once.ownTags)).toBe(BODY);
	});

	it("keeps the user's lines and tags, removing only its own", () => {
		const existing = "---\nrating: 5\ntags:\n  - daily\n---\n" + BODY;
		const once = applyFrontmatter(existing, fields({ tags: ["remarkable/x"] }), []);
		expect(removeFrontmatter(once.content, once.ownTags)).toBe(existing);
	});

	it("leaves a note that carries nothing of the plugin's alone", () => {
		expect(removeFrontmatter(BODY, [])).toBeNull();
		expect(removeFrontmatter("---\nrating: 5\n---\n" + BODY, [])).toBeNull();
	});

	it("clears an inline tags list of exactly its own entries", () => {
		const existing = "---\ntags: [daily]\n---\n" + BODY;
		const once = applyFrontmatter(existing, fields({ tags: ["remarkable/x"] }), []);
		expect(removeFrontmatter(once.content, once.ownTags)).toBe(existing);
	});

	it("drops an inline tags key that held only its own entries", () => {
		const existing = "---\nrating: 5\ntags: [remarkable/x]\n---\n" + BODY;
		expect(removeFrontmatter(existing, ["remarkable/x"])).toBe("---\nrating: 5\n---\n" + BODY);
	});

	it("reads a double-quoted entry as the tag it quotes", () => {
		const existing = '---\ntags: ["remarkable/x", daily]\n---\n' + BODY;
		const { content } = applyFrontmatter(existing, fields({ tags: ["remarkable/x"] }), ["remarkable/x"]);
		expect(content).toContain('tags: ["remarkable/x", daily]\n');
	});
});

describe("value formatting", () => {
	it("formats a local minute, zero-padded", () => {
		expect(formatLocalMinute(new Date(2026, 7, 5, 9, 3))).toBe("2026-08-05T09:03");
	});

	it("reads the device's epoch-milliseconds string", () => {
		const epoch = String(Date.UTC(2026, 7, 25, 12, 0));
		expect(deviceModified(epoch)).toBe(formatLocalMinute(new Date(Number(epoch))));
	});

	it("tolerates an ISO string and refuses junk instead of writing Invalid Date", () => {
		expect(deviceModified("2026-08-25T12:00:00.000Z")).toBe(formatLocalMinute(new Date("2026-08-25T12:00:00.000Z")));
		expect(deviceModified("soon")).toBeNull();
	});

	it("namespaces device tags the way Obsidian properties want them: no #, no spaces, deduped", () => {
		expect(namespacedTags(["#work", "Projekt X", "work", "  "])).toEqual(["remarkable/work", "remarkable/Projekt-X"]);
	});
});

describe("the gate", () => {
	it("locks free and opens for a trial or a licence", () => {
		expect(frontmatterAllowed(entitlementOf(NO_LICENCE, NOW))).toBe(false);
		expect(frontmatterAllowed(entitlementOf(startTrial(NO_LICENCE, NOW), NOW))).toBe(true);
		expect(frontmatterAllowed({ tier: "pro", since: "2026-01-01", stale: false })).toBe(true);
	});
});
